package main

import sim "github.com/micmonay/simconnect"

var simvars = map[string]func(args ...interface{}) sim.SimVar{
	"ANGLE OF ATTACK INDICATOR": sim.SimVarAngleOfAttackIndicator,
	//"GUN AMMO":,
	//"CANNON AMMO" : ,
	//"ROCKET AMMO": sim.SimvarRoc ,
	//"BOMB AMMO": sim.SimvarBomb ,
	"LIGHT ON STATES": sim.SimVarLightOnStates,
	"LIGHT STATES":    sim.SimVarLightStates,
	"LIGHT PANEL":     sim.SimVarLightPanel,
	"LIGHT STROBE":    sim.SimVarLightStrobe,
	"LIGHT LANDING":   sim.SimVarLightLanding,
	//"STROBE FLASH": sim.Simvarstrobef ,
	"LIGHT TAXI":                  sim.SimVarLightTaxi,
	"LIGHT BEACON":                sim.SimVarLightBeacon,
	"LIGHT NAV":                   sim.SimVarLightNav,
	"LIGHT LOGO":                  sim.SimVarLightLogo,
	"LIGHT WING":                  sim.SimVarLightWing,
	"LIGHT RECOGNITION":           sim.SimVarLightRecognition,
	"LIGHT CABIN":                 sim.SimVarLightCabin,
	"LANDING LIGHT PBH":           sim.SimVarLandingLightPbh,
	"LIGHT NAV ON":                sim.SimVarLightNavOn,
	"LIGHT BEACON ON":             sim.SimVarLightBeaconOn,
	"LIGHT LANDING ON":            sim.SimVarLightLandingOn,
	"LIGHT TAXI ON":               sim.SimVarLightTaxiOn,
	"LIGHT STROBE ON":             sim.SimVarLightStrobeOn,
	"LIGHT PANEL ON":              sim.SimVarLightPanelOn,
	"LIGHT RECOGNITION ON":        sim.SimVarLightRecognitionOn,
	"LIGHT WING ON":               sim.SimVarLightWingOn,
	"LIGHT LOGO ON":               sim.SimVarLightLogoOn,
	"LIGHT CABIN ON":              sim.SimVarLightCabinOn,
	"LIGHT HEAD ON":               sim.SimVarLightHeadOn,
	"LIGHT BRAKE ON":              sim.SimVarLightBrakeOn,
	"WHEEL RPM":                   sim.SimVarWheelRpm,
	"CENTER WHEEL RPM":            sim.SimVarCenterWheelRpm,
	"LEFT WHEEL RPM":              sim.SimVarLeftWheelRpm,
	"RIGHT WHEEL RPM":             sim.SimVarRightWheelRpm,
	"AUX WHEEL RPM":               sim.SimVarAuxWheelRpm,
	"WHEEL ROTATION ANGLE":        sim.SimVarWheelRotationAngle,
	"CENTER WHEEL ROTATION ANGLE": sim.SimVarCenterWheelRotationAngle,
	"LEFT WHEEL ROTATION ANGLE":   sim.SimVarLeftWheelRotationAngle,
	"RIGHT WHEEL ROTATION ANGLE":  sim.SimVarRightWheelRotationAngle,
	"AUX WHEEL ROTATION ANGLE":    sim.SimVarAuxWheelRotationAngle,
	"SIGMA SQRT":                  sim.SimVarSigmaSqrt,
	"DYNAMIC PRESSURE":            sim.SimVarDynamicPressure,
	"TOTAL VELOCITY":              sim.SimVarTotalVelocity,
	"TOTAL WORLD VELOCITY":        sim.SimVarTotalWorldVelocity,
	"GROUND VELOCITY":             sim.SimVarGroundVelocity,
	//"SURFACE RELATIVE GROUND SPEED":              sim.SimVarSurfacerela,
	"AIRSPEED TRUE":                     sim.SimVarAirspeedTrue,
	"AIRSPEED INDICATED":                sim.SimVarAirspeedIndicated,
	"AIRSPEED SELECT INDICATED OR TRUE": sim.SimVarAirspeedSelectIndicatedOrTrue,
	"AIRSPEED TRUE CALIBRATE":           sim.SimVarAirspeedTrueCalibrate,
	"AIRSPEED BARBER POLE":              sim.SimVarAirspeedBarberPole,
	"AIRSPEED MACH":                     sim.SimVarAirspeedMach,
	"VERTICAL SPEED":                    sim.SimVarVerticalSpeed,
	"VARIOMETER RATE":                   sim.SimVarVariometerRate,
	"VARIOMETER SWITCH":                 sim.SimVarVariometerSwitch,
	"MACH MAX OPERATE":                  sim.SimVarMachMaxOperate,
	"STALL WARNING":                     sim.SimVarStallWarning,
	"OVERSPEED WARNING":                 sim.SimVarOverspeedWarning,
	"BARBER POLE MACH":                  sim.SimVarBarberPoleMach,
	"VELOCITY BODY X":                   sim.SimVarVelocityBodyX,
	"VELOCITY BODY Y":                   sim.SimVarVelocityBodyY,
	"VELOCITY BODY Z":                   sim.SimVarVelocityBodyZ,
	"VELOCITY WORLD X":                  sim.SimVarVelocityWorldX,
	"VELOCITY WORLD Y":                  sim.SimVarVelocityWorldY,
	"VELOCITY WORLD Z":                  sim.SimVarVelocityWorldZ,
	"RELATIVE WIND VELOCITY BODY X":     sim.SimVarRelativeWindVelocityBodyX,
	"RELATIVE WIND VELOCITY BODY Y":     sim.SimVarRelativeWindVelocityBodyY,
	"RELATIVE WIND VELOCITY BODY Z":     sim.SimVarRelativeWindVelocityBodyZ,
	"ACCELERATION WORLD X":              sim.SimVarAccelerationWorldX,
	"ACCELERATION WORLD Y":              sim.SimVarAccelerationWorldY,
	"ACCELERATION WORLD Z":              sim.SimVarAccelerationWorldZ,
	"ACCELERATION BODY X":               sim.SimVarAccelerationBodyX,
	"ACCELERATION BODY Y":               sim.SimVarAccelerationBodyY,
	"ACCELERATION BODY Z":               sim.SimVarAccelerationBodyZ,
	"ROTATION VELOCITY BODY X":          sim.SimVarRotationVelocityBodyX,
	"ROTATION VELOCITY BODY Y":          sim.SimVarRotationVelocityBodyY,
	"ROTATION VELOCITY BODY Z":          sim.SimVarRotationVelocityBodyZ,
	"DESIGN SPEED VS0":                  sim.SimVarDesignSpeedVs0,
	"DESIGN SPEED VS1":                  sim.SimVarDesignSpeedVs1,
	"DESIGN SPEED VC":                   sim.SimVarDesignSpeedVc,
	//"DESIGN SPEED MIN ROTATION":                  sim.Simvardesign,
	//"DESIGN SPEED CLIMB":                         sim.Simvardesspeecl,
	//"DESIGN CRUISE ALT":                          sim.Simvardesignc,
	//"DESIGN TAKEOFF SPEED":                       sim.Simvardesita,
	//"AI CONTROLS":                                sim.Simvarcontr,
	//"DELEGATE CONTROLS TO AI":                    sim.Simvardela,
	"MIN DRAG VELOCITY":                 sim.SimVarMinDragVelocity,
	"PLANE LATITUDE":                    sim.SimVarPlaneLatitude,
	"PLANE LONGITUDE":                   sim.SimVarPlaneLongitude,
	"PLANE ALTITUDE":                    sim.SimVarPlaneAltitude,
	"PLANE ALT ABOVE GROUND":            sim.SimVarPlaneAltAboveGround,
	"PLANE PITCH DEGREES":               sim.SimVarPlanePitchDegrees,
	"PLANE BANK DEGREES":                sim.SimVarPlaneBankDegrees,
	"PLANE HEADING DEGREES MAGNETIC":    sim.SimVarPlaneHeadingDegreesMagnetic,
	"PLANE HEADING DEGREES TRUE":        sim.SimVarPlaneHeadingDegreesTrue,
	"INDICATED ALTITUDE":                sim.SimVarIndicatedAltitude,
	"PRESSURE ALTITUDE":                 sim.SimVarPressureAltitude,
	"KOHLSMAN SETTING MB":               sim.SimVarKohlsmanSettingMb,
	"KOHLSMAN SETTING HG":               sim.SimVarKohlsmanSettingHg,
	"ATTITUDE INDICATOR PITCH DEGREES":  sim.SimVarAttitudeIndicatorPitchDegrees,
	"ATTITUDE INDICATOR BANK DEGREES":   sim.SimVarAttitudeIndicatorBankDegrees,
	"ATTITUDE BARS POSITION":            sim.SimVarAttitudeBarsPosition,
	"ATTITUDE CAGE":                     sim.SimVarAttitudeCage,
	"MAGVAR":                            sim.SimVarMagvar,
	"WISKEY COMPASS INDICATION DEGREES": sim.SimVarWiskeyCompassIndicationDegrees,
	"MAGNETIC COMPASS":                  sim.SimVarMagneticCompass,
	"PLANE HEADING DEGREES GYRO":        sim.SimVarPlaneHeadingDegreesGyro,
	"GYRO DRIFT ERROR":                  sim.SimVarGyroDriftError,
	"DELTA HEADING RATE":                sim.SimVarDeltaHeadingRate,
	"TURN INDICATOR RATE":               sim.SimVarTurnIndicatorRate,
	"TURN INDICATOR SWITCH":             sim.SimVarTurnIndicatorSwitch,
	"GROUND ALTITUDE":                   sim.SimVarGroundAltitude,
	"SIM ON GROUND":                     sim.SimVarSimOnGround,
	//"SIM SHOULD SET ON GROUND":                   sim.Simvarshou,
	"TURN COORDINATOR BALL":              sim.SimVarTurnCoordinatorBall,
	"YOKE Y POSITION":                    sim.SimVarYokeYPosition,
	"YOKE Y INDICATOR":                   sim.SimVarYokeYIndicator,
	"YOKE X POSITION":                    sim.SimVarYokeXPosition,
	"YOKE X INIDICATOR":                  sim.SimVarYokeXIndicator,
	"YOKE X INDICATOR":                   sim.SimVarYokeXIndicator,
	"AILERON POSITION":                   sim.SimVarAileronPosition,
	"RUDDER PEDAL POSITION":              sim.SimVarRudderPedalPosition,
	"RUDDER PEDAL INDICATOR":             sim.SimVarRudderPedalIndicator,
	"RUDDER POSITION":                    sim.SimVarRudderPosition,
	"ELEVATOR POSITION":                  sim.SimVarElevatorPosition,
	"ELEVATOR TRIM POSITION":             sim.SimVarElevatorTrimPosition,
	"ELEVATOR TRIM INDICATOR":            sim.SimVarElevatorTrimIndicator,
	"ELEVATOR TRIM PCT":                  sim.SimVarElevatorTrimPct,
	"BRAKE LEFT POSITION":                sim.SimVarBrakeLeftPosition,
	"BRAKE RIGHT POSITION":               sim.SimVarBrakeRightPosition,
	"BRAKE INDICATOR":                    sim.SimVarBrakeIndicator,
	"BRAKE PARKING POSITION":             sim.SimVarBrakeParkingPosition,
	"BRAKE PARKING INDICATOR":            sim.SimVarBrakeParkingIndicator,
	"BRAKE DEPENDENT HYDRAULIC PRESSURE": sim.SimVarBrakeDependentHydraulicPressure,
	"SPOILERS ARMED":                     sim.SimVarSpoilersArmed,
	"SPOILERS HANDLE POSITION":           sim.SimVarSpoilersHandlePosition,
	"SPOILERS LEFT POSITION":             sim.SimVarSpoilersLeftPosition,
	"SPOILERS RIGHT POSITION":            sim.SimVarSpoilersRightPosition,
	"FLY BY WIRE ELAC SWITCH":            sim.SimVarFlyByWireElacSwitch,
	"FLY BY WIRE FAC SWITCH":             sim.SimVarFlyByWireFacSwitch,
	"FLY BY WIRE SEC SWITCH":             sim.SimVarFlyByWireSecSwitch,
	"FLY BY WIRE ELAC FAILED":            sim.SimVarFlyByWireElacFailed,
	"FLY BY WIRE FAC FAILED":             sim.SimVarFlyByWireFacFailed,
	"FLY BY WIRE SEC FAILED":             sim.SimVarFlyByWireSecFailed,
	//"FLY BY WIRE ALPHA PROTECTION":               sim.Simvarfbw,
	"FLAPS NUM HANDLE POSITIONS":        sim.SimVarFlapsNumHandlePositions,
	"FLAPS HANDLE PERCENT":              sim.SimVarFlapsHandlePercent,
	"FLAPS HANDLE INDEX":                sim.SimVarFlapsHandleIndex,
	"TRAILING EDGE FLAPS LEFT PERCENT":  sim.SimVarTrailingEdgeFlapsLeftPercent,
	"TRAILING EDGE FLAPS RIGHT PERCENT": sim.SimVarTrailingEdgeFlapsRightPercent,
	"LEADING EDGE FLAPS LEFT PERCENT":   sim.SimVarLeadingEdgeFlapsLeftPercent,
	"LEADING EDGE FLAPS RIGHT PERCENT":  sim.SimVarLeadingEdgeFlapsRightPercent,
	"TRAILING EDGE FLAPS LEFT ANGLE":    sim.SimVarTrailingEdgeFlapsLeftAngle,
	"TRAILING EDGE FLAPS RIGHT ANGLE":   sim.SimVarTrailingEdgeFlapsRightAngle,
	"LEADING EDGE FLAPS LEFT ANGLE":     sim.SimVarLeadingEdgeFlapsLeftAngle,
	"LEADING EDGE FLAPS RIGHT ANGLE":    sim.SimVarLeadingEdgeFlapsRightAngle,
	//"FLAP POSITION SET":                          sim.SimVarflapse,
	"IS GEAR RETRACTABLE":            sim.SimVarIsGearRetractable,
	"IS GEAR WHEELS":                 sim.SimVarIsGearWheels,
	"IS GEAR SKIS":                   sim.SimVarIsGearSkis,
	"IS GEAR FLOATS":                 sim.SimVarIsGearFloats,
	"IS GEAR SKIDS":                  sim.SimVarIsGearSkids,
	"GEAR HANDLE POSITION":           sim.SimVarGearHandlePosition,
	"GEAR EMERGENCY HANDLE POSITION": sim.SimVarGearEmergencyHandlePosition,
	"GEAR CENTER POSITION":           sim.SimVarGearCenterPosition,
	"GEAR LEFT POSITION":             sim.SimVarGearLeftPosition,
	"GEAR RIGHT POSITION":            sim.SimVarGearRightPosition,
	"GEAR TAIL POSITION":             sim.SimVarGearTailPosition,
	"GEAR AUX POSITION":              sim.SimVarGearAuxPosition,
	"GEAR POSITION":                  sim.SimVarGearPosition,
	"GEAR ANIMATION POSITION":        sim.SimVarGearAnimationPosition,
	"GEAR TOTAL PCT EXTENDED":        sim.SimVarGearTotalPctExtended,
	"GEAR WARNING":                   sim.SimVarGearWarning,
	"TAILWHEEL LOCK ON":              sim.SimVarTailwheelLockOn,
	//"NOSEWHEEL LOCK ON":                          sim.Simvarn,
	//"COWL FLAPS":                                 sim.Simvarcow,
	"AVIONICS MASTER SWITCH":             sim.SimVarAvionicsMasterSwitch,
	"PANEL AUTO FEATHER SWITCH":          sim.SimVarPanelAutoFeatherSwitch,
	"PANEL ANTI ICE SWITCH":              sim.SimVarPanelAntiIceSwitch,
	"AUTO BRAKE SWITCH CB":               sim.SimVarAutoBrakeSwitchCb,
	"ANTISKID BRAKES ACTIVE":             sim.SimVarAntiskidBrakesActive,
	"WATER RUDDER HANDLE POSITION":       sim.SimVarWaterRudderHandlePosition,
	"WATER LEFT RUDDER EXTENDED":         sim.SimVarWaterLeftRudderExtended,
	"WATER RIGHT RUDDER EXTENDED":        sim.SimVarWaterRightRudderExtended,
	"RETRACT FLOAT SWITCH":               sim.SimVarRetractFloatSwitch,
	"RETRACT LEFT FLOAT EXTENDED":        sim.SimVarRetractLeftFloatExtended,
	"RETRACT RIGHT FLOAT EXTENDED":       sim.SimVarRetractRightFloatExtended,
	"GEAR CENTER STEER ANGLE":            sim.SimVarGearCenterSteerAngle,
	"GEAR LEFT STEER ANGLE":              sim.SimVarGearLeftSteerAngle,
	"GEAR RIGHT STEER ANGLE":             sim.SimVarGearRightSteerAngle,
	"GEAR AUX STEER ANGLE":               sim.SimVarGearAuxSteerAngle,
	"GEAR STEER ANGLE":                   sim.SimVarGearSteerAngle,
	"WATER LEFT RUDDER STEER ANGLE":      sim.SimVarWaterLeftRudderSteerAngle,
	"WATER RIGHT RUDDER STEER ANGLE":     sim.SimVarWaterRightRudderSteerAngle,
	"GEAR CENTER STEER ANGLE PCT":        sim.SimVarGearCenterSteerAnglePct,
	"GEAR LEFT STEER ANGLE PCT":          sim.SimVarGearLeftSteerAnglePct,
	"GEAR RIGHT STEER ANGLE PCT":         sim.SimVarGearRightSteerAnglePct,
	"GEAR AUX STEER ANGLE PCT":           sim.SimVarGearAuxSteerAnglePct,
	"GEAR STEER ANGLE PCT":               sim.SimVarGearSteerAnglePct,
	"WATER LEFT RUDDER STEER ANGLE PCT":  sim.SimVarWaterLeftRudderSteerAnglePct,
	"WATER RIGHT RUDDER STEER ANGLE PCT": sim.SimVarWaterRightRudderSteerAnglePct,
	"STEER INPUT CONTROL":                sim.SimVarSteerInputControl,
	"ELEVATOR DEFLECTION":                sim.SimVarElevatorDeflection,
	"ELEVATOR DEFLECTION PCT":            sim.SimVarElevatorDeflectionPct,
	"AILERON LEFT DEFLECTION":            sim.SimVarAileronLeftDeflection,
	"AILERON LEFT DEFLECTION PCT":        sim.SimVarAileronLeftDeflectionPct,
	"AILERON RIGHT DEFLECTION":           sim.SimVarAileronRightDeflection,
	"AILERON RIGHT DEFLECTION PCT":       sim.SimVarAileronRightDeflectionPct,
	"AILERON AVERAGE DEFLECTION":         sim.SimVarAileronAverageDeflection,
	"AILERON TRIM":                       sim.SimVarAileronTrim,
	"AILERON TRIM PCT":                   sim.SimVarAileronTrimPct,
	"RUDDER DEFLECTION":                  sim.SimVarRudderDeflection,
	"RUDDER DEFLECTION PCT":              sim.SimVarRudderDeflectionPct,
	"RUDDER TRIM":                        sim.SimVarRudderTrim,
	"RUDDER TRIM PCT":                    sim.SimVarRudderTrimPct,
	"WING FLEX PCT":                      sim.SimVarWingFlexPct,
	"WING AREA":                          sim.SimVarWingArea,
	"WING SPAN":                          sim.SimVarWingSpan,
	"PROP SYNC ACTIVE":                   sim.SimVarPropSyncActive,
	"INCIDENCE ALPHA":                    sim.SimVarIncidenceAlpha,
	"INCIDENCE BETA":                     sim.SimVarIncidenceBeta,
	"BETA DOT":                           sim.SimVarBetaDot,
	"LINEAR CL ALPHA":                    sim.SimVarLinearClAlpha,
	"STALL ALPHA":                        sim.SimVarStallAlpha,
	"ZERO LIFT ALPHA":                    sim.SimVarZeroLiftAlpha,
	"CG PERCENT":                         sim.SimVarCgPercent,
	"CG PERCENT LATERAL":                 sim.SimVarCgPercentLateral,
	"CG AFT LIMIT":                       sim.SimVarCgAftLimit,
	"CG FWD LIMIT":                       sim.SimVarCgFwdLimit,
	"CG MAX MACH":                        sim.SimVarCgMaxMach,
	"CG MIN MACH":                        sim.SimVarCgMinMach,
	"PAYLOAD STATION WEIGHT":             sim.SimVarPayloadStationWeight,
	"PAYLOAD STATION NAME":               sim.SimVarPayloadStationName,
	"PAYLOAD STATION COUNT":              sim.SimVarPayloadStationCount,
	"PAYLOAD STATION OBJECT":             sim.SimVarPayloadStationObject,
	"PAYLOAD STATION NUM SIMOBJECTS":     sim.SimVarPayloadStationNumSimobjects,
	"ELEVON DEFLECTION":                  sim.SimVarElevonDeflection,
	"FOLDING WING LEFT PERCENT":          sim.SimVarFoldingWingLeftPercent,
	"FOLDING WING RIGHT PERCENT":         sim.SimVarFoldingWingRightPercent,
	//"FOLDING WING HANDLE POSITION":               sim.Simvarfw,
	"CANOPY OPEN":       sim.SimVarCanopyOpen,
	"TAILHOOK POSITION": sim.SimVarTailhookPosition,
	//"TAILHOOK HANDLE":                            sim.Simvartailhan,
	"LAUNCHBAR POSITION": sim.SimVarLaunchbarPosition,
	//"LAUNCHBAR SWITCH":                           sim.Simvarlaunchbars,
	//"LAUNCHBAR HELD EXTENDED":                    sim.Simvar,
	"EXIT OPEN":                      sim.SimVarExitOpen,
	"EXIT TYPE":                      sim.SimVarExitType,
	"EXIT POSX":                      sim.SimVarExitPosx,
	"EXIT POSY":                      sim.SimVarExitPosy,
	"EXIT POSZ":                      sim.SimVarExitPosz,
	"RADIO HEIGHT":                   sim.SimVarRadioHeight,
	"DECISION HEIGHT":                sim.SimVarDecisionHeight,
	"DECISION ALTITUDE MSL":          sim.SimVarDecisionAltitudeMsl,
	"TOTAL WEIGHT":                   sim.SimVarTotalWeight,
	"MAX GROSS WEIGHT":               sim.SimVarMaxGrossWeight,
	"EMPTY WEIGHT":                   sim.SimVarEmptyWeight,
	"EMPTY WEIGHT PITCH MOI":         sim.SimVarEmptyWeightPitchMoi,
	"EMPTY WEIGHT ROLL MOI":          sim.SimVarEmptyWeightRollMoi,
	"EMPTY WEIGHT YAW MOI":           sim.SimVarEmptyWeightYawMoi,
	"EMPTY WEIGHT CROSS COUPLED MOI": sim.SimVarEmptyWeightCrossCoupledMoi,
	"TOTAL WEIGHT PITCH MOI":         sim.SimVarTotalWeightPitchMoi,
	"TOTAL WEIGHT ROLL MOI":          sim.SimVarTotalWeightRollMoi,
	"TOTAL WEIGHT YAW MOI":           sim.SimVarTotalWeightYawMoi,
	"TOTAL WEIGHT CROSS COUPLED MOI": sim.SimVarTotalWeightCrossCoupledMoi,
	"WATER BALLAST VALVE":            sim.SimVarWaterBallastValve,
	"AUTOPILOT MASTER":               sim.SimVarAutopilotMaster,
	"AUTOPILOT WING LEVELER":         sim.SimVarAutopilotWingLeveler,
	"AUTOPILOT NAV1 LOCK":            sim.SimVarAutopilotNav1Lock,
	"AUTOPILOT HEADING LOCK":         sim.SimVarAutopilotHeadingLock,
	"AUTOPILOT HEADING LOCK DIR":     sim.SimVarAutopilotHeadingLockDir,
	"AUTOPILOT ALTITUDE LOCK":        sim.SimVarAutopilotAltitudeLock,
	"AUTOPILOT ALTITUDE LOCK VAR":    sim.SimVarAutopilotAltitudeLockVar,
	"AUTOPILOT ALTITUDE HOLD":        sim.SimVarAutopilotAltitudeLock,
	"AUTOPILOT GLIDESLOPE HOLD":      sim.SimVarAutopilotGlideslopeHold,
	"AUTOPILOT APPROACH HOLD":        sim.SimVarAutopilotApproachHold,
	"AUTOPILOT BACKCOURSE HOLD":      sim.SimVarAutopilotBackcourseHold,
	"AUTOPILOT YAW DAMPER":           sim.SimVarAutopilotYawDamper,
	"AUTOPILOT AIRSPEED HOLD":        sim.SimVarAutopilotAirspeedHold,
	"AUTOPILOT AIRSPEED HOLD VAR":    sim.SimVarAutopilotAirspeedHoldVar,
	"AUTOPILOT MACH HOLD":            sim.SimVarAutopilotMachHold,
	"AUTOPILOT MACH HOLD VAR":        sim.SimVarAutopilotMachHoldVar,
	"AUTOPILOT VERTICAL HOLD":        sim.SimVarAutopilotVerticalHold,
	"AUTOPILOT VERTICAL HOLD VAR":    sim.SimVarAutopilotVerticalHoldVar,
	//"AUTOPILOT ALTITUDE MANUALLY TUNABLE":        sim.Simvaraltitudem,
	//"AUTOPILOT HEADING MANUALLY TUNABLE":         sim.Simvarheadingm,
	"AUTOPILOT THROTTLE ARM":         sim.SimVarAutopilotThrottleArm,
	"AUTOPILOT TAKEOFF POWER ACTIVE": sim.SimVarAutopilotTakeoffPowerActive,
	"AUTOPILOT RPM HOLD":             sim.SimVarAutopilotRpmHold,
	"AUTOPILOT RPM HOLD VAR":         sim.SimVarAutopilotRpmHoldVar,
	//"AUTOPILOT SPEED SETTING":                    sim.Simvarautos,
	//"AUTOPILOT AIRSPEED ACQUISITION":             sim.Simvarautoai
	//"AUTOPILOT AIRSPEED HOLD CURRENT":            sim.Simvar,
	//"AUTOPILOT MAX SPEED HOLD":                   sim.Simvarautomax,
	//"AUTOPILOT CRUISE SPEED HOLD":                sim.Simvarautocruises,
	"AUTOPILOT FLIGHT DIRECTOR ACTIVE": sim.SimVarAutopilotFlightDirectorActive,
	"AUTOPILOT FLIGHT DIRECTOR PITCH":  sim.SimVarAutopilotFlightDirectorPitch,
	"AUTOPILOT FLIGHT DIRECTOR BANK":   sim.SimVarAutopilotFlightDirectorBank,
	"AUTOPILOT PITCH HOLD":             sim.SimVarAutopilotPitchHold,
	"AUTOPILOT PITCH HOLD REF":         sim.SimVarAutopilotPitchHoldRef,
	"AUTOPILOT NAV SELECTED":           sim.SimVarAutopilotNavSelected,
	"GPS DRIVES NAV1":                  sim.SimVarGpsDrivesNav1,
	"AUTOTHROTTLE ACTIVE":              sim.SimVarAutothrottleActive,
	"AUTOPILOT MAX BANK":               sim.SimVarAutopilotMaxBank,
	"NUMBER OF CATAPULTS":              sim.SimVarNumberOfCatapults,
	"HOLDBACK BAR INSTALLED":           sim.SimVarHoldbackBarInstalled,
	"BLAST SHIELD POSITION":            sim.SimVarBlastShieldPosition,
	//"CATAPULT STROKE POSITION":                   sim.Simvarcata,
	"ENGINE CONTROL SELECT": sim.SimVarEngineControlSelect,
	"NUMBER OF ENGINES":     sim.SimVarNumberOfEngines,
	"MAX RATED ENGINE RPM":  sim.SimVarMaxRatedEngineRpm,
	//"PROPELLER ADVANCED SELECTION":               sim.Simvaradvance,
	"THROTTLE LOWER LIMIT": sim.SimVarThrottleLowerLimit,
	//OIL AMOUNT":                                 sim.Simvaroil,
	//"ENGINE PRIMER":                              sim.Simvarenginep,
	"ENGINE TYPE":                          sim.SimVarEngineType,
	"ENG RPM ANIMATION PERCENT":            sim.SimVarEngRpmAnimationPercent,
	"FULL THROTTLE THRUST TO WEIGHT RATIO": sim.SimVarFullThrottleThrustToWeightRatio,
	"PROP RPM":                             sim.SimVarPropRpm,
	"PROP MAX RPM PERCENT":                 sim.SimVarPropMaxRpmPercent,
	"PROP THRUST":                          sim.SimVarPropThrust,
	"PROP BETA":                            sim.SimVarPropBeta,
	"PROP FEATHERING INHIBIT":              sim.SimVarPropFeatheringInhibit,
	"PROP FEATHERED":                       sim.SimVarPropFeathered,
	"PROP SYNC DELTA LEVER":                sim.SimVarPropSyncDeltaLever,
	"PROP AUTO FEATHER ARMED":              sim.SimVarPropAutoFeatherArmed,
	"PROP FEATHER SWITCH":                  sim.SimVarPropFeatherSwitch,
	"PROP AUTO CRUISE ACTIVE":              sim.SimVarPropAutoCruiseActive,
	"PROP ROTATION ANGLE":                  sim.SimVarPropRotationAngle,
	"PROP BETA MAX":                        sim.SimVarPropBetaMax,
	"PROP BETA MIN":                        sim.SimVarPropBetaMax,
	"PROP BETA MIN REVERSE":                sim.SimVarPropBetaMinReverse,
	"MASTER IGNITION SWITCH":               sim.SimVarMasterIgnitionSwitch,
	"ENG COMBUSTION":                       sim.SimVarEngCombustion,
	//"OLD ENG STARTER":                            sim.SimVarOld,
	"ENG N1 RPM": sim.SimVarEngN1Rpm,
	"ENG N2 RPM": sim.SimVarEngN2Rpm,
	//"ENG FUEL FLOW GPH":                          sim.Simvarengfuelfl,
	"ENG FUEL FLOW PPH": sim.SimVarEngFuelFlowPph,
	//"ENG FUEL FLOW PPH SSL":                      sim.Simvarengfuelpph,
	"ENG TORQUE":         sim.SimVarEngTorque,
	"ENG ANTI ICE":       sim.SimVarEngAntiIce,
	"ENG PRESSURE RATIO": sim.SimVarEngPressureRatio,
	//"ENG PRESSURE RATIO GES":                     sim.Simvarengpressurerati,
	"ENG EXHAUST GAS TEMPERATURE":     sim.SimVarEngExhaustGasTemperature,
	"ENG EXHAUST GAS TEMPERATURE GES": sim.SimVarEngExhaustGasTemperatureGes,
	//"ENG CYLINDER HEAD TEMPERATURE":              sim.SimVarEngCylinderHead,
	"ENG OIL TEMPERATURE":                  sim.SimVarEngOilTemperature,
	"ENG OIL PRESSURE":                     sim.SimVarEngOilPressure,
	"ENG OIL QUANTITY":                     sim.SimVarEngOilQuantity,
	"ENG HYDRAULIC PRESSURE":               sim.SimVarHydraulicPressure,
	"ENG HYDRAULIC QUANTITY":               sim.SimVarEngHydraulicQuantity,
	"ENG MANIFOLD PRESSURE":                sim.SimVarEngManifoldPressure,
	"ENG VIBRATION":                        sim.SimVarEngVibration,
	"ENG RPM SCALER":                       sim.SimVarEngRpmScaler,
	"ENG TURBINE TEMPERATURE":              sim.SimVarEngTurbineTemperature,
	"ENG TORQUE PERCENT":                   sim.SimVarEngTorquePercent,
	"ENG FUEL PRESSURE":                    sim.SimVarEngFuelPressure,
	"ENG ELECTRICAL LOAD":                  sim.SimVarEngElectricalLoad,
	"ENG TRANSMISSION PRESSURE":            sim.SimVarEngTransmissionPressure,
	"ENG TRANSMISSION TEMPERATURE":         sim.SimVarEngTransmissionTemperature,
	"ENG ROTOR RPM":                        sim.SimVarEngRotorRpm,
	"ENG FUEL FLOW BUG POSITION":           sim.SimVarEngFuelFlowBugPosition,
	"ENG MAX RPM":                          sim.SimVarEngMaxRpm,
	"ENG ON FIRE":                          sim.SimVarEngOnFire,
	"GENERAL ENG COMBUSTION":               sim.SimVarGeneralEngCombustion,
	"GENERAL ENG MASTER ALTERNATOR":        sim.SimVarGeneralEngMasterAlternator,
	"GENERAL ENG FUEL PUMP SWITCH":         sim.SimVarGeneralEngFuelPumpSwitch,
	"GENERAL ENG FUEL PUMP ON":             sim.SimVarGeneralEngFuelPumpOn,
	"GENERAL ENG RPM":                      sim.SimVarGeneralEngRpm,
	"GENERAL ENG PCT MAX RPM":              sim.SimVarGeneralEngPctMaxRpm,
	"GENERAL ENG MAX REACHED RPM":          sim.SimVarGeneralEngMaxReachedRpm,
	"GENERAL ENG THROTTLE LEVER POSITION":  sim.SimVarGeneralEngThrottleLeverPosition,
	"GENERAL ENG MIXTURE LEVER POSITION":   sim.SimVarGeneralEngMixtureLeverPosition,
	"GENERAL ENG PROPELLER LEVER POSITION": sim.SimVarGeneralEngPropellerLeverPosition,
	"GENERAL ENG STARTER":                  sim.SimVarGeneralEngStarter,
	"GENERAL ENG STARTER ACTIVE":           sim.SimVarGeneralEngStarterActive,
	"GENERAL ENG EXHAUST GAS TEMPERATURE":  sim.SimVarEngExhaustGasTemperature,
	"GENERAL ENG OIL PRESSURE":             sim.SimVarGeneralEngOilPressure,
	"GENERAL ENG OIL LEAKED PERCENT":       sim.SimVarGeneralEngOilLeakedPercent,
	"GENERAL ENG COMBUSTION SOUND PERCENT": sim.SimVarGeneralEngCombustionSoundPercent,
	"GENERAL ENG DAMAGE PERCENT":           sim.SimVarGeneralEngDamagePercent,
	"GENERAL ENG OIL TEMPERATURE":          sim.SimVarGeneralEngOilTemperature,
	"GENERAL ENG FAILED":                   sim.SimVarGeneralEngFailed,
	"GENERAL ENG GENERATOR SWITCH":         sim.SimVarGeneralEngGeneratorSwitch,
	"GENERAL ENG GENERATOR ACTIVE":         sim.SimVarGeneralEngGeneratorActive,
	"GENERAL ENG ANTI ICE POSITION":        sim.SimVarGeneralEngAntiIcePosition,
	"GENERAL ENG FUEL VALVE":               sim.SimVarGeneralEngFuelValve,
	"GENERAL ENG FUEL PRESSURE":            sim.SimVarGeneralEngFuelPressure,
	"GENERAL ENG ELAPSED TIME":             sim.SimVarGeneralEngElapsedTime,
	//"GENERAL ENG FIRE DETECTED":                  sim.Simvargeneengdete,
	"GENERAL ENG FUEL USED SINCE START":          sim.SimVarGeneralEngFuelUsedSinceStart,
	"RECIP ENG COWL FLAP POSITION":               sim.SimVarRecipEngCowlFlapPosition,
	"RECIP ENG PRIMER":                           sim.SimVarRecipEngPrimer,
	"RECIP ENG MANIFOLD PRESSURE":                sim.SimVarEngManifoldPressure,
	"RECIP ENG ALTERNATE AIR POSITION":           sim.SimVarRecipEngAlternateAirPosition,
	"RECIP ENG COOLANT RESERVOIR PERCENT":        sim.SimVarRecipEngCoolantReservoirPercent,
	"RECIP ENG LEFT MAGNETO":                     sim.SimVarRecipEngLeftMagneto,
	"RECIP ENG RIGHT MAGNETO":                    sim.SimVarRecipEngRightMagneto,
	"RECIP ENG BRAKE POWER":                      sim.SimVarRecipEngBrakePower,
	"RECIP ENG STARTER TORQUE":                   sim.SimVarRecipEngStarterTorque,
	"RECIP ENG TURBOCHARGER FAILED":              sim.SimVarRecipEngTurbochargerFailed,
	"RECIP ENG EMERGENCY BOOST ACTIVE":           sim.SimVarRecipEngEmergencyBoostActive,
	"RECIP ENG EMERGENCY BOOST ELAPSED TIME":     sim.SimVarRecipEngEmergencyBoostElapsedTime,
	"RECIP ENG WASTEGATE POSITION":               sim.SimVarRecipEngWastegatePosition,
	"RECIP ENG TURBINE INLET TEMPERATURE":        sim.SimVarRecipEngTurbineInletTemperature,
	"RECIP ENG CYLINDER HEAD TEMPERATURE":        sim.SimVarEngCylinderHeadTemperature,
	"RECIP ENG RADIATOR TEMPERATURE":             sim.SimVarRecipEngRadiatorTemperature,
	"RECIP ENG FUEL AVAILABLE":                   sim.SimVarRecipEngFuelAvailable,
	"RECIP ENG FUEL FLOW":                        sim.SimVarRecipEngFuelFlow,
	"RECIP ENG FUEL TANK SELECTOR":               sim.SimVarFuelTankSelector,
	"RECIP ENG FUEL TANKS USED":                  sim.SimVarRecipEngFuelTanksUsed,
	"RECIP ENG FUEL NUMBER TANKS USED":           sim.SimVarRecipEngFuelNumberTanksUsed,
	"RECIP ENG DETONATING":                       sim.SimVarRecipEngDetonating,
	"RECIP ENG CYLINDER HEALTH":                  sim.SimVarRecipEngCylinderHealth,
	"RECIP ENG NUM CYLINDERS":                    sim.SimVarRecipEngNumCylinders,
	"RECIP ENG NUM CYLINDERS FAILED":             sim.SimVarRecipEngNumCylindersFailed,
	"RECIP CARBURETOR TEMPERATURE":               sim.SimVarRecipCarburetorTemperature,
	"RECIP MIXTURE RATIO":                        sim.SimVarRecipMixtureRatio,
	"RECIP ENG ANTIDETONATION TANK VALVE":        sim.SimVarRecipEngAntidetonationTankValve,
	"RECIP ENG ANTIDETONATION TANK QUANTITY":     sim.SimVarRecipEngAntidetonationTankQuantity,
	"RECIP ENG ANTIDETONATION TANK MAX QUANTITY": sim.SimVarRecipEngAntidetonationTankMaxQuantity,
	"RECIP ENG NITROUS TANK VALVE":               sim.SimVarRecipEngNitrousTankValve,
	"RECIP ENG NITROUS TANK QUANTITY":            sim.SimVarRecipEngNitrousTankQuantity,
	"RECIP ENG NITROUS TANK MAX QUANTITY":        sim.SimVarRecipEngNitrousTankMaxQuantity,
	"TURB ENG N1":                                sim.SimVarTurbEngN1,
	"TURB ENG N2":                                sim.SimVarTurbEngN2,
	"TURB ENG CORRECTED N1":                      sim.SimVarTurbEngCorrectedN1,
	"TURB ENG CORRECTED N2":                      sim.SimVarTurbEngCorrectedN2,
	"TURB ENG CORRECTED FF":                      sim.SimVarTurbEngCorrectedFf,
	"TURB ENG MAX TORQUE PERCENT":                sim.SimVarTurbEngMaxTorquePercent,
	"TURB ENG PRESSURE RATIO":                    sim.SimVarTurbEngPressureRatio,
	"TURB ENG ITT":                               sim.SimVarTurbEngItt,
	"TURB ENG AFTERBURNER":                       sim.SimVarTurbEngAfterburner,
	//"TURB ENG AFTERBURNER STAGE ACTIVE":          sim.Simvar,
	//"TURB ENG AFTERBURNER PCT ACTIVE":            sim.Simvarafter,
	"TURB ENG JET THRUST":             sim.SimVarTurbEngJetThrust,
	"TURB ENG BLEED AIR":              sim.SimVarTurbEngBleedAir,
	"TURB ENG TANK SELECTOR":          sim.SimVarTurbEngTankSelector,
	"TURB ENG TANKS USED":             sim.SimVarTurbEngTanksUsed,
	"TURB ENG NUM TANKS USED":         sim.SimVarTurbEngNumTanksUsed,
	"TURB ENG FUEL FLOW PPH":          sim.SimVarTurbEngFuelFlowPph,
	"TURB ENG FUEL AVAILABLE":         sim.SimVarTurbEngFuelAvailable,
	"TURB ENG PRIMARY NOZZLE PERCENT": sim.SimVarTurbEngPrimaryNozzlePercent,
	"TURB ENG REVERSE NOZZLE PERCENT": sim.SimVarTurbEngReverseNozzlePercent,
	"TURB ENG VIBRATION":              sim.SimVarEngVibration,
	//"TURB ENG IGNITION SWITCH":                 sim.Simvarigni,
	"TURB ENG MASTER STARTER SWITCH": sim.SimVarTurbEngMasterStarterSwitch,
	"ENG FAILED":                     sim.SimVarEngFailed,
	"PARTIAL PANEL ADF":              sim.SimVarPartialPanelAdf,
	"PARTIAL PANEL AIRSPEED":         sim.SimVarPartialPanelAirspeed,
	"PARTIAL PANEL ALTIMETER":        sim.SimVarPartialPanelAltimeter,
	//"PARTIAL PANEL ATTITUDE":                   sim.SimVarPartialPanelAl,
	"PARTIAL PANEL COMM":              sim.SimVarPartialPanelComm,
	"PARTIAL PANEL COMPASS":           sim.SimVarPartialPanelCompass,
	"PARTIAL PANEL ELECTRICAL":        sim.SimVarPartialPanelElectrical,
	"PARTIAL PANEL AVIONICS":          sim.SimVarPartialPanelAvionics,
	"PARTIAL PANEL ENGINE":            sim.SimVarPartialPanelEngine,
	"PARTIAL PANEL FUEL INDICATOR":    sim.SimVarPartialPanelFuelIndicator,
	"PARTIAL PANEL HEADING":           sim.SimVarPartialPanelHeading,
	"PARTIAL PANEL VERTICAL VELOCITY": sim.SimVarPartialPanelVerticalVelocity,
	"PARTIAL PANEL TRANSPONDER":       sim.SimVarPartialPanelTransponder,
	"PARTIAL PANEL NAV":               sim.SimVarPartialPanelNav,
	"PARTIAL PANEL PITOT":             sim.SimVarPartialPanelPitot,
	"PARTIAL PANEL TURN COORDINATOR":  sim.SimVarPartialPanelTurnCoordinator,
	"PARTIAL PANEL VACUUM":            sim.SimVarPartialPanelVacuum,
	"FUEL TANK CENTER LEVEL":          sim.SimVarFuelTankCenterLevel,
	"FUEL TANK CENTER CAPACITY":       sim.SimVarFuelTankCenterCapacity,
	"FUEL TANK CENTER QUANTITY":       sim.SimVarFuelTankCenterQuantity,
	"FUEL TANK CENTER2 LEVEL":         sim.SimVarFuelTankCenter2Level,
	"FUEL TANK CENTER2 CAPACITY":      sim.SimVarFuelTankCenter2Quantity,
	"FUEL TANK CENTER2 QUANTITY":      sim.SimVarFuelTankCenter2Quantity,
	"FUEL TANK CENTER3 LEVEL":         sim.SimVarFuelTankCenter3Level,
	"FUEL TANK CENTER3 CAPACITY":      sim.SimVarFuelTankCenter3Capacity,
	"FUEL TANK CENTER3 QUANTITY":      sim.SimVarFuelTankCenter3Quantity,
	"FUEL TANK LEFT MAIN LEVEL":       sim.SimVarFuelTankLeftMainLevel,
	"FUEL TANK LEFT MAIN CAPACITY":    sim.SimVarFuelTankLeftMainCapacity,
	"FUEL TANK LEFT MAIN QUANTITY":    sim.SimVarFuelTankLeftMainQuantity,
	"FUEL TANK LEFT AUX LEVEL":        sim.SimVarFuelTankLeftAuxLevel,
	"FUEL TANK LEFT AUX CAPACITY":     sim.SimVarFuelTankLeftAuxCapacity,
	"FUEL TANK LEFT AUX QUANTITY":     sim.SimVarFuelTankLeftAuxQuantity,
	"FUEL TANK LEFT TIP LEVEL":        sim.SimVarFuelTankLeftTipLevel,
	"FUEL TANK LEFT TIP CAPACITY":     sim.SimVarFuelTankLeftTipCapacity,
	"FUEL TANK LEFT TIP QUANTITY":     sim.SimVarFuelTankLeftTipQuantity,
	"FUEL LEFT QUANTITY":              sim.SimVarFuelLeftQuantity,
	"FUEL TANK RIGHT MAIN LEVEL":      sim.SimVarFuelTankRightMainLevel,
	"FUEL TANK RIGHT MAIN CAPACITY":   sim.SimVarFuelTankRightMainCapacity,
	"FUEL TANK RIGHT MAIN QUANTITY":   sim.SimVarFuelTankRightMainQuantity,
	"FUEL TANK RIGHT AUX LEVEL":       sim.SimVarFuelTankRightAuxLevel,
	"FUEL TANK RIGHT AUX CAPACITY":    sim.SimVarFuelTankRightAuxCapacity,
	"FUEL TANK RIGHT AUX QUANTITY":    sim.SimVarFuelTankRightAuxQuantity,
	"FUEL TANK RIGHT TIP LEVEL":       sim.SimVarFuelTankRightTipLevel,
	"FUEL TANK RIGHT TIP CAPACITY":    sim.SimVarFuelTankRightTipCapacity,
	"FUEL TANK RIGHT TIP QUANTITY":    sim.SimVarFuelTankRightTipQuantity,
	"FUEL RIGHT QUANTITY":             sim.SimVarFuelRightQuantity,
	"FUEL TANK EXTERNAL1 LEVEL":       sim.SimVarFuelTankExternal1Level,
	"FUEL TANK EXTERNAL1 CAPACITY":    sim.SimVarFuelTankExternal1Capacity,
	"FUEL TANK EXTERNAL1 QUANTITY":    sim.SimVarFuelTankExternal1Quantity,
	"FUEL TANK EXTERNAL2 LEVEL":       sim.SimVarFuelTankExternal2Level,
	"FUEL TANK EXTERNAL2 CAPACITY":    sim.SimVarFuelTankExternal2Capacity,
	"FUEL TANK EXTERNAL2 QUANTITY":    sim.SimVarFuelTankExternal2Quantity,
	"FUEL TOTAL QUANTITY":             sim.SimVarFuelTotalQuantity,
	"FUEL TOTAL CAPACITY":             sim.SimVarFuelTotalCapacity,
	"FUEL LEFT CAPACITY":              sim.SimVarFuelLeftCapacity,
	"FUEL RIGHT CAPACITY":             sim.SimVarFuelRightCapacity,
	"FUEL WEIGHT PER GALLON":          sim.SimVarFuelWeightPerGallon,
	"FUEL TANK SELECTOR":              sim.SimVarFuelTankSelector,
	"FUEL CROSS FEED":                 sim.SimVarFuelCrossFeed,
	"NUM FUEL SELECTORS":              sim.SimVarNumFuelSelectors,
	"FUEL SELECTED QUANTITY PERCENT":  sim.SimVarFuelSelectedQuantityPercent,
	"FUEL SELECTED QUANTITY":          sim.SimVarFuelSelectedQuantity,
	"FUEL TOTAL QUANTITY WEIGHT":      sim.SimVarFuelTotalQuantityWeight,
	"FUEL SELECTED TRANSFER MODE":     sim.SimVarFuelSelectedTransferMode,
	//"FUEL DUMP SWITCH":                         sim.Simvarfueldu,
	//"FUEL DUMP ACTIVE":                         sim.Simvar,
	"DROPPABLE OBJECTS COUNT":   sim.SimVarDroppableObjectsCount,
	"DROPPABLE OBJECTS TYPE":    sim.SimVarDroppableObjectsType,
	"DROPPABLE OBJECTS UI NAME": sim.SimVarDroppableObjectsUiName,
	//"WARNING FUEL":                             sim.Simvarwarfu,
	//"WARNING FUEL LEFT":                        sim.Simvarwarningfuel,
	//"WARNING FUEL RIGHT":                       sim.Simvar,
	//"WARNING VACUUM":                           sim.Simvarwarningva,
	//"WARNING VACUUM LEFT":                      sim.Simvar,
	//"WARNING VACUUM RIGHT":                     sim.Simvar,
	//"WARNING OIL PRESSURE":                     sim.Simvarwarnioil,
	//"WARNING VOLTAGE":                          sim.Simvarwarningv,
	//"WARNING LOW HEIGHT":                       sim.Simvarwarninglow,
	"AUTOPILOT AVAILABLE":     sim.SimVarAutopilotAvailable,
	"FLAPS AVAILABLE":         sim.SimVarFlapsAvailable,
	"STALL HORN AVAILABLE":    sim.SimVarStallHornAvailable,
	"ENGINE MIXURE AVAILABLE": sim.SimVarEngineMixureAvailable,
	"CARB HEAT AVAILABLE":     sim.SimVarCarbHeatAvailable,
	"SPOILER AVAILABLE":       sim.SimVarSpoilerAvailable,
	"STROBES AVAILABLE":       sim.SimVarStrobesAvailable,
	//"PROP TYPE AVAILABLE":                      sim.Simvarproptyoe,
	"TOE BRAKES AVAILABLE": sim.SimVarToeBrakesAvailable,
	"IS TAIL DRAGGER":      sim.SimVarIsTailDragger,
	//"SYSTEMS AVAILABLE":                        sim.Simvarsystav,
	//"INSTRUMENTS AVAILABLE":                    sim.Simvarinstrumenav,
	//"FUEL PUMP":                                sim.SimVarfuelp,
	"MANUAL FUEL PUMP HANDLE":            sim.SimVarManualFuelPumpHandle,
	"ALTERNATE STATIC SOURCE OPEN":       sim.SimVarAlternateStaticSourceOpen,
	"BLEED AIR SOURCE CONTROL":           sim.SimVarBleedAirSourceControl,
	"ELECTRICAL MASTER BATTERY":          sim.SimVarElectricalMasterBattery,
	"ELECTRICAL OLD CHARGING AMPS":       sim.SimVarElectricalOldChargingAmps,
	"ELECTRICAL TOTAL LOAD AMPS":         sim.SimVarElectricalTotalLoadAmps,
	"ELECTRICAL BATTERY LOAD":            sim.SimVarElectricalBatteryLoad,
	"ELECTRICAL BATTERY VOLTAGE":         sim.SimVarElectricalBatteryVoltage,
	"ELECTRICAL MAIN BUS VOLTAGE":        sim.SimVarElectricalMainBusVoltage,
	"ELECTRICAL MAIN BUS AMPS":           sim.SimVarElectricalMainBusVoltage,
	"ELECTRICAL AVIONICS BUS VOLTAGE":    sim.SimVarElectricalAvionicsBusVoltage,
	"ELECTRICAL AVIONICS BUS AMPS":       sim.SimVarElectricalAvionicsBusAmps,
	"ELECTRICAL HOT BATTERY BUS VOLTAGE": sim.SimVarElectricalHotBatteryBusVoltage,
	"ELECTRICAL HOT BATTERY BUS AMPS":    sim.SimVarElectricalHotBatteryBusAmps,
	"ELECTRICAL BATTERY BUS VOLTAGE":     sim.SimVarElectricalBatteryBusVoltage,
	"ELECTRICAL BATTERY BUS AMPS":        sim.SimVarElectricalBatteryBusAmps,
	"ELECTRICAL GENALT BUS VOLTAGE":      sim.SimVarElectricalGenaltBusVoltage,
	"ELECTRICAL GENALT BUS AMPS":         sim.SimVarElectricalGenaltBusAmps,
	"CIRCUIT GENERAL PANEL ON":           sim.SimVarCircuitGeneralPanelOn,
	"CIRCUIT FLAP MOTOR ON":              sim.SimVarCircuitFlapMotorOn,
	"CIRCUIT GEAR MOTOR ON":              sim.SimVarCircuitGearMotorOn,
	"CIRCUIT AUTOPILOT ON":               sim.SimVarCircuitAutopilotOn,
	"CIRCUIT AVIONICS ON":                sim.SimVarCircuitAvionicsOn,
	"CIRCUIT PITOT HEAT ON":              sim.SimVarCircuitPitotHeatOn,
	"CIRCUIT PROP SYNC ON":               sim.SimVarCircuitPropSyncOn,
	"CIRCUIT AUTO FEATHER ON":            sim.SimVarCircuitAutoFeatherOn,
	//"CIRCUIT AUTO BRAKES ON":                   sim.Simvarautobrakeso,
	"CIRCUIT STANDY VACUUM ON":        sim.SimVarCircuitStandyVacuumOn,
	"CIRCUIT STANDBY VACUUM ON":       sim.SimVarCircuitStandyVacuumOn,
	"CIRCUIT MARKER BEACON ON":        sim.SimVarCircuitMarkerBeaconOn,
	"CIRCUIT GEAR WARNING ON":         sim.SimVarCircuitGearWarningOn,
	"CIRCUIT HYDRAULIC PUMP ON":       sim.SimVarCircuitHydraulicPumpOn,
	"AMBIENT DENSITY":                 sim.SimVarAmbientDensity,
	"AMBIENT TEMPERATURE":             sim.SimVarAmbientTemperature,
	"AMBIENT PRESSURE":                sim.SimVarAmbientPressure,
	"AMBIENT WIND VELOCITY":           sim.SimVarAmbientWindVelocity,
	"AMBIENT WIND DIRECTION":          sim.SimVarAmbientWindDirection,
	"AMBIENT WIND X":                  sim.SimVarAmbientWindX,
	"AMBIENT WIND Y":                  sim.SimVarAmbientWindY,
	"AMBIENT WIND Z":                  sim.SimVarAmbientWindZ,
	"AMBIENT PRECIP STATE":            sim.SimVarAmbientPrecipState,
	"AMBIENT IN CLOUD":                sim.SimVarAmbientInCloud,
	"AMBIENT VISIBILITY":              sim.SimVarAmbientVisibility,
	"BAROMETER PRESSURE":              sim.SimVarBarometerPressure,
	"SEA LEVEL PRESSURE":              sim.SimVarSeaLevelPressure,
	"TOTAL AIR TEMPERATURE":           sim.SimVarTotalAirTemperature,
	"STANDARD ATM TEMPERATURE":        sim.SimVarStandardAtmTemperature,
	"AIRCRAFT WIND X":                 sim.SimVarAircraftWindX,
	"AIRCRAFT WIND Y":                 sim.SimVarAircraftWindY,
	"AIRCRAFT WIND Z":                 sim.SimVarAircraftWindZ,
	"HYDRAULIC PRESSURE":              sim.SimVarHydraulicPressure,
	"HYDRAULIC RESERVOIR PERCENT":     sim.SimVarHydraulicReservoirPercent,
	"HYDRAULIC SYSTEM INTEGRITY":      sim.SimVarHydraulicSystemIntegrity,
	"HYDRAULIC SWITCH":                sim.SimVarHydraulicSwitch,
	"GEAR HYDRAULIC PRESSURE":         sim.SimVarGearHydraulicPressure,
	"CONCORDE VISOR NOSE HANDLE":      sim.SimVarConcordeVisorNoseHandle,
	"CONCORDE VISOR POSITION PERCENT": sim.SimVarConcordeVisorPositionPercent,
	"CONCORDE NOSE ANGLE":             sim.SimVarConcordeNoseAngle,
	//"RADIOS AVAILABLE":                         sim.Simvarrad,
	"COM TRANSMIT":          sim.SimVarComTransmit,
	"COM RECEIVE ALL":       sim.SimVarComReceiveAll,
	"COM RECIEVE ALL":       sim.SimVarComRecieveAll,
	"NAV SOUND":             sim.SimVarNavSound,
	"DME SOUND":             sim.SimVarDmeSound,
	"ADF SOUND":             sim.SimVarAdfSound,
	"ADF CARD":              sim.SimVarAdfCard,
	"MARKER SOUND":          sim.SimVarMarkerSound,
	"COM AVAILABLE":         sim.SimVarComAvailable,
	"COM ACTIVE FREQUENCY":  sim.SimVarComActiveFrequency,
	"COM STANDBY FREQUENCY": sim.SimVarComStandbyFrequency,
	"COM STATUS":            sim.SimVarComStatus,
	"COM TEST":              sim.SimVarComTest,
	"TRANSPONDER AVAILABLE": sim.SimVarTransponderAvailable,
	"TRANSPONDER CODE":      sim.SimVarTransponderCode,
	"ADF AVAILABLE":         sim.SimVarAdfAvailable,
	"ADF FREQUENCY":         sim.SimVarAdfFrequency,
	"ADF EXT FREQUENCY":     sim.SimVarAdfExtFrequency,
	"ADF ACTIVE FREQUENCY":  sim.SimVarAdfActiveFrequency,
	"ADF STANDBY FREQUENCY": sim.SimVarAdfStandbyFrequency,
	"ADF LATLONALT":         sim.SimVarAdfLatlonalt,
	"ADF SIGNAL":            sim.SimVarAdfSignal,
	"ADF RADIAL":            sim.SimVarAdfRadial,
	"ADF IDENT":             sim.SimVarAdfIdent,
	"ADF NAME":              sim.SimVarAdfName,
	"NAV AVAILABLE":         sim.SimVarNavAvailable,
	"NAV ACTIVE FREQUENCY":  sim.SimVarNavActiveFrequency,
	"NAV STANDBY FREQUENCY": sim.SimVarNavStandbyFrequency,
	"NAV SIGNAL":            sim.SimVarNavSignal,
	"NAV IDENT":             sim.SimVarNavIdent,
	"NAV NAME":              sim.SimVarNavName,
	"NAV CODES":             sim.SimVarNavCodes,
	"NAV HAS NAV":           sim.SimVarNavHasNav,
	"NAV HAS LOCALIZER":     sim.SimVarNavHasLocalizer,
	"NAV HAS DME":           sim.SimVarNavHasDme,
	"NAV HAS GLIDE SLOPE":   sim.SimVarNavHasGlideSlope,
	"NAV BACK COURSE FLAGS": sim.SimVarNavBackCourseFlags,
	//"NAV MAGVAR":                               sim.Simvarnav,
	"NAV RADIAL":                      sim.SimVarNavRadial,
	"NAV RADIAL ERROR":                sim.SimVarNavRadialError,
	"NAV LOCALIZER":                   sim.SimVarNavLocalizer,
	"NAV GLIDE SLOPE":                 sim.SimVarNavGlideSlope,
	"NAV GLIDE SLOPE ERROR":           sim.SimVarNavGlideSlopeError,
	"NAV CDI":                         sim.SimVarNavCdi,
	"NAV GSI":                         sim.SimVarNavGsi,
	"NAV TOFROM":                      sim.SimVarNavTofrom,
	"NAV GS FLAG":                     sim.SimVarNavGsFlag,
	"NAV OBS":                         sim.SimVarNavObs,
	"NAV DME":                         sim.SimVarNavDme,
	"NAV DMESPEED":                    sim.SimVarNavDmespeed,
	"NAV VOR LATLONALT":               sim.SimVarNavVorLatlonalt,
	"NAV GS LATLONALT":                sim.SimVarNavGsLatlonalt,
	"NAV DME LATLONALT":               sim.SimVarNavDmeLatlonalt,
	"NAV RELATIVE BEARING TO STATION": sim.SimVarNavRelativeBearingToStation,
	"MARKER BEACON STATE":             sim.SimVarMarkerBeaconState,
	"INNER MARKER":                    sim.SimVarInnerMarker,
	"MIDDLE MARKER":                   sim.SimVarMiddleMarker,
	"OUTER MARKER":                    sim.SimVarOuterMarker,
	"INNER MARKER LATLONALT":          sim.SimVarInnerMarkerLatlonalt,
	"MIDDLE MARKER LATLONALT":         sim.SimVarMiddleMarkerLatlonalt,
	"OUTER MARKER LATLONALT":          sim.SimVarOuterMarkerLatlonalt,
	"SELECTED DME":                    sim.SimVarSelectedDme,
	"REALISM":                         sim.SimVarRealism,
	"AUTO COORDINATION":               sim.SimVarAutoCoordination,
	"UNLIMITED FUEL":                  sim.SimVarUnlimitedFuel,
	"REALISM CRASH WITH OTHERS":       sim.SimVarRealismCrashWithOthers,
	"REALISM CRASH DETECTION":         sim.SimVarRealismCrashDetection,
	"MANUAL INSTRUMENT LIGHTS":        sim.SimVarManualInstrumentLights,
	"TRUE AIRSPEED SELECTED":          sim.SimVarTrueAirspeedSelected,
	"ATC TYPE":                        sim.SimVarAtcType,
	"ATC MODEL":                       sim.SimVarAtcModel,
	"ATC HEAVY":                       sim.SimVarAtcHeavy,
	"ATC ID":                          sim.SimVarAtcId,
	"ATC AIRLINE":                     sim.SimVarAtcAirline,
	"ATC FLIGHT NUMBER":               sim.SimVarAtcFlightNumber,
	"STRUCT LATLONALT":                sim.SimVarStructLatlonalt,
	"STRUCT LATLONALTPBH":             sim.SimVarStructLatlonaltpbh,
	//"STRUCT PBH32":                             sim.Simvarstructpb,
	//"STRUCT DAMAGEVISIBLE":                     sim.Simvarstructd,
	"STRUCT SURFACE RELATIVE VELOCITY": sim.SimVarStructSurfaceRelativeVelocity,
	"STRUCT WORLDVELOCITY":             sim.SimVarStructWorldvelocity,
	"STRUCT WORLD ROTATION VELOCITY":   sim.SimVarStructWorldRotationVelocity,
	"STRUCT BODY VELOCITY":             sim.SimVarStructBodyVelocity,
	"STRUCT BODY ROTATION VELOCITY":    sim.SimVarStructBodyRotationVelocity,
	//"STRUCT BODY ROTATION ACCELERATION":        sim.Simvarstrbodyrotata,
	"STRUCT WORLD ACCELERATION": sim.SimVarStructWorldAcceleration,
	"STRUCT ENGINE POSITION":    sim.SimVarStructEnginePosition,
	"STRUCT AMBIENT WIND":       sim.SimVarStructAmbientWind,
	//"STRUCT REALISM VARS":                      sim.Simvarstrure,
	//"STRUC HEADING HOLD PID CONSTS":            sim.Simvarstruche,
	//"STRUC AIRSPEED HOLD PID CONSTS":           sim.Simvarstruair,
	"STRUCT EYEPOINT DYNAMIC ANGLE":  sim.SimVarStructEyepointDynamicAngle,
	"STRUCT EYEPOINT DYNAMIC OFFSET": sim.SimVarStructEyepointDynamicOffset,
	"PITOT HEAT":                     sim.SimVarPitotHeat,
	"PITOT ICE PCT":                  sim.SimVarPitotIcePct,
	"SMOKE ENABLE":                   sim.SimVarSmokeEnable,
	"SMOKESYSTEM AVAILABLE":          sim.SimVarSmokesystemAvailable,
	"G FORCE":                        sim.SimVarGForce,
	//"SEMIBODY LOADFACTOR X":                    sim.Simvarsemla,
	"SEMIBODY LOADFACTOR Y": sim.SimVarSemibodyLoadfactorY,
	//"SEMIBODY LOADFACTOR Z":                    sim.Simvar,
	//"SEMIBODY LOADFACTOR YDOT":                 sim.Simvar,
	"MAX G FORCE":          sim.SimVarMaxGForce,
	"MIN G FORCE":          sim.SimVarMinGForce,
	"SUCTION PRESSURE":     sim.SimVarSuctionPressure,
	"RAD INS SWITCH":       sim.SimVarRadInsSwitch,
	"TYPICAL DESCENT RATE": sim.SimVarTypicalDescentRate,
	"VISUAL MODEL RADIUS":  sim.SimVarVisualModelRadius,
	"SIMULATED RADIUS":     sim.SimVarSimulatedRadius,
	//"IS USER SIM":                              sim.Simvaridsi,
	//"CONTROLLABLE":                             sim.Simvarcontr,
	"HEADING INDICATOR":                  sim.SimVarHeadingIndicator,
	"TITLE":                              sim.SimVarTitle,
	"CATEGORY":                           sim.SimVarCategory,
	"SIM DISABLED":                       sim.SimVarSimDisabled,
	"PROP DEICE SWITCH":                  sim.SimVarPropDeiceSwitch,
	"STRUCTURAL DEICE SWITCH":            sim.SimVarStructuralDeiceSwitch,
	"STRUCTURAL ICE PCT":                 sim.SimVarStructuralIcePct,
	"ARTIFICIAL GROUND ELEVATION":        sim.SimVarArtificialGroundElevation,
	"SURFACE INFO VALID":                 sim.SimVarSurfaceInfoValid,
	"SURFACE TYPE":                       sim.SimVarSurfaceType,
	"SURFACE CONDITION":                  sim.SimVarSurfaceCondition,
	"PUSHBACK STATE":                     sim.SimVarPushbackState,
	"PUSHBACK ANGLE":                     sim.SimVarPushbackAngle,
	"PUSHBACK CONTACTX":                  sim.SimVarPushbackContactx,
	"PUSHBACK CONTACTY":                  sim.SimVarPushbackContacty,
	"PUSHBACK CONTACTZ":                  sim.SimVarPushbackContactz,
	"PUSHBACK WAIT":                      sim.SimVarPushbackWait,
	"HSI CDI NEEDLE":                     sim.SimVarHsiCdiNeedle,
	"HSI GSI NEEDLE":                     sim.SimVarHsiGsiNeedle,
	"HSI CDI NEEDLE VALID":               sim.SimVarHsiCdiNeedleValid,
	"HSI GSI NEEDLE VALID":               sim.SimVarHsiGsiNeedleValid,
	"HSI TF FLAGS":                       sim.SimVarHsiTfFlags,
	"HSI BEARING":                        sim.SimVarHsiBearing,
	"HSI BEARING VALID":                  sim.SimVarHsiBearingValid,
	"HSI HAS LOCALIZER":                  sim.SimVarHsiHasLocalizer,
	"HSI SPEED":                          sim.SimVarHsiSpeed,
	"HSI DISTANCE":                       sim.SimVarHsiDistance,
	"HSI STATION IDENT":                  sim.SimVarHsiStationIdent,
	"IS SLEW ACTIVE":                     sim.SimVarIsSlewActive,
	"IS SLEW ALLOWED":                    sim.SimVarIsSlewAllowed,
	"ATC SUGGESTED MIN RWY TAKEOFF":      sim.SimVarAtcSuggestedMinRwyTakeoff,
	"ATC SUGGESTED MIN RWY LANDING":      sim.SimVarAtcSuggestedMinRwyLanding,
	"YAW STRING ANGLE":                   sim.SimVarYawStringAngle,
	"YAW STRING PCT EXTENDED":            sim.SimVarYawStringPctExtended,
	"INDUCTOR COMPASS PERCENT DEVIATION": sim.SimVarInductorCompassPercentDeviation,
	"INDUCTOR COMPASS HEADING REF":       sim.SimVarInductorCompassHeadingRef,
	"ANEMOMETER PCT RPM":                 sim.SimVarAnemometerPctRpm,
	"GPS POSITION LAT":                   sim.SimVarGpsPositionLat,
	"GPS POSITION LON":                   sim.SimVarGpsPositionLon,
	"GPS POSITION ALT":                   sim.SimVarGpsPositionAlt,
	"GPS MAGVAR":                         sim.SimVarGpsMagvar,
	"GPS IS ACTIVE FLIGHT PLAN":          sim.SimVarGpsIsActiveFlightPlan,
	"GPS IS ACTIVE WAY POINT":            sim.SimVarGpsIsActiveWayPoint,
	"GPS IS ARRIVED":                     sim.SimVarGpsIsArrived,
	"GPS IS DIRECTTO FLIGHTPLAN":         sim.SimVarGpsIsDirecttoFlightplan,
	"GPS GROUND SPEED":                   sim.SimVarGpsGroundSpeed,
	"GPS GROUND TRUE HEADING":            sim.SimVarGpsGroundTrueHeading,
	"GPS GROUND MAGNETIC TRACK":          sim.SimVarGpsGroundMagneticTrack,
	"GPS GROUND TRUE TRACK":              sim.SimVarGpsGroundTrueTrack,
	"GPS ETE":                            sim.SimVarGpsEte,
	"GPS ETA":                            sim.SimVarGpsEta,
	"GPS WP DISTANCE":                    sim.SimVarGpsWpDistance,
	"GPS WP BEARING":                     sim.SimVarGpsWpBearing,
	"GPS WP TRUE BEARING":                sim.SimVarGpsWpTrueBearing,
	"GPS WP CROSS TRK":                   sim.SimVarGpsWpCrossTrk,
	"GPS WP DESIRED TRACK":               sim.SimVarGpsWpDesiredTrack,
	"GPS WP TRUE REQ HDG":                sim.SimVarGpsWpTrueReqHdg,
	"GPS WP VERTICAL SPEED":              sim.SimVarGpsWpVerticalSpeed,
	"GPS WP TRACK ANGLE ERROR":           sim.SimVarGpsWpTrackAngleError,
	"GPS WP NEXT ID":                     sim.SimVarGpsWpNextId,
	"GPS WP NEXT LAT":                    sim.SimVarGpsWpNextLat,
	"GPS WP NEXT LON":                    sim.SimVarGpsWpNextLon,
	"GPS WP NEXT ALT":                    sim.SimVarGpsWpNextAlt,
	"GPS WP PREV VALID":                  sim.SimVarGpsWpPrevValid,
	"GPS WP PREV ID":                     sim.SimVarGpsWpPrevId,
	"GPS WP PREV LAT":                    sim.SimVarGpsWpPrevLat,
	"GPS WP PREV LON":                    sim.SimVarGpsWpPrevLon,
	"GPS WP PREV ALT":                    sim.SimVarGpsWpPrevAlt,
	"GPS WP ETE":                         sim.SimVarGpsWpEte,
	"GPS WP ETA":                         sim.SimVarGpsWpEta,
	/*
		"GPS COURSE TO STEER":                      sim.Simvar,
		"GPS FLIGHT PLAN WP INDEX":                 sim.Simvar,
		"GPS FLIGHT PLAN WP COUNT":                 sim.Simvar,
		"GPS IS ACTIVE WP LOCKED":                  sim.Simvar,
		"GPS IS APPROACH LOADED":                   sim.Simvar,
		"GPS IS APPROACH ACTIVE":                   sim.Simvar,
		"GPS APPROACH MODE":                        sim.Simvar,
		"GPS APPROACH WP TYPE":                     sim.Simvar,
		"GPS APPROACH IS WP RUNWAY":                sim.Simvar,
		"GPS APPROACH SEGMENT TYPE":                sim.Simvar,
		"GPS APPROACH AIRPORT ID":                  sim.Simvar,
		"GPS APPROACH APPROACH INDEX":              sim.Simvar,
		"GPS APPROACH APPROACH ID":                 sim.Simvar,
		"GPS APPROACH APPROACH TYPE":               sim.Simvar,
		"GPS APPROACH TRANSITION INDEX":            sim.Simvar,
		"GPS APPROACH TRANSITION ID":               sim.Simvar,
		"GPS APPROACH IS FINAL":                    sim.Simvar,
		"GPS APPROACH IS MISSED":                   sim.Simvar,
		"GPS APPROACH TIMEZONE DEVIATION":          sim.Simvar,
		"GPS APPROACH WP INDEX":                    sim.Simvar,
		"GPS APPROACH WP COUNT":                    sim.Simvar,
		"GPS TARGET DISTANCE":                      sim.Simvar,
		"GPS TARGET ALTITUDE":                      sim.Simvar,
		"USER INPUT ENABLED":                       sim.Simvar,
		"ROTOR BRAKE HANDLE POS":                   sim.Simvar,
		"ROTOR BRAKE ACTIVE":                       sim.Simvar,
		"ROTOR CLUTCH SWITCH POS":                  sim.Simvar,
		"ROTOR CLUTCH ACTIVE":                      sim.Simvar,
		"ROTOR TEMPERATURE":                        sim.Simvar,
		"ROTOR CHIP DETECTED":                      sim.Simvar,
		"ROTOR GOV SWITCH POS":                     sim.Simvar,
		"ROTOR GOV ACTIVE":                         sim.Simvar,
		"ROTOR LATERAL TRIM PCT":                   sim.Simvar,
		"ROTOR RPM PCT":                            sim.Simvar,
		"ROTOR ROTATION ANGLE":                     sim.Simvar,
		"COLLECTIVE POSITION":                      sim.Simvar,
		"DISK PITCH ANGLE":                         sim.Simvar,
		"DISK BANK ANGLE":                          sim.Simvar,
		"DISK PITCH PCT":                           sim.Simvar,
		"DISK BANK PCT":                            sim.Simvar,
		"DISK CONING PCT":                          sim.Simvar,
		"GEAR DAMAGE BY SPEED":                     sim.Simvar,
		"GEAR SPEED EXCEEDED":                      sim.Simvar,
		"FLAP DAMAGE BY SPEED":                     sim.Simvar,
		"FLAP SPEED EXCEEDED":                      sim.Simvar,
		"ESTIMATED CRUISE SPEED":                   sim.Simvar,
		"ESTIMATED FUEL FLOW":                      sim.Simvar,
		"EYEPOINT POSITION":                        sim.Simvar,
		"NAV VOR LLAF64":                           sim.Simvar,
		"NAV GS LLAF64":                            sim.Simvar,
		"NAV RAW GLIDE SLOPE":                      sim.Simvar,
		"WINDSHIELD RAIN EFFECT AVAILABLE":         sim.Simvar,
		"STATIC CG TO GROUND":                      sim.Simvar,
		"STATIC PITCH":                             sim.Simvar,
		"CRASH SEQUENCE":                           sim.Simvar,
		"CRASH FLAG":                               sim.Simvar,
		"APPLY HEAT TO SYSTEMS":                    sim.Simvar,
		"TOW RELEASE HANDLE":                       sim.Simvar,
		"TOW CONNECTION":                           sim.Simvar,
		"APU PCT RPM":                              sim.Simvar,
		"APU PCT STARTER":                          sim.Simvar,
		"APU VOLTS":                                sim.Simvar,
		"APU GENERATOR SWITCH":                     sim.Simvar,
		"APU GENERATOR ACTIVE":                     sim.Simvar,
		"APU ON FIRE DETECTED":                     sim.Simvar,
		"PRESSURIZATION CABIN ALTITUDE":            sim.Simvar,
		"PRESSURIZATION CABIN ALTITUDE GOAL":       sim.Simvar,
		"PRESSURIZATION CABIN ALTITUDE RATE":       sim.Simvar,
		"PRESSURIZATION PRESSURE DIFFERENTIAL":     sim.Simvar,
		"PRESSURIZATION DUMP SWITCH":               sim.Simvar,
		"FIRE BOTTLE SWITCH":                       sim.Simvar,
		"FIRE BOTTLE DISCHARGED":                   sim.Simvar,
		"CABIN NO SMOKING ALERT SWITCH":            sim.Simvar,
		"CABIN SEATBELTS ALERT SWITCH":             sim.Simvar,
		"GPWS WARNING":                             sim.Simvar,
		"GPWS SYSTEM ACTIVE":                       sim.Simvar,
		"IS LATITUDE LONGITUDE FREEZE ON":          sim.Simvar,
		"IS ALTITUDE FREEZE ON":                    sim.Simvar,
		"IS ATTITUDE FREEZE ON":                    sim.Simvar,
		"NUM SLING CABLES":                         sim.Simvar,
		"SLING OBJECT ATTACHED":                    sim.Simvar,
		"SLING CABLE BROKEN":                       sim.Simvar,
		"SLING CABLE EXTENDED LENGTH":              sim.Simvar,
		"SLING ACTIVE PAYLOAD STATION":             sim.Simvar,
		"SLING HOIST PERCENT DEPLOYED":             sim.Simvar,
		"SLING HOIST SWITCH":                       sim.Simvar,
		"SLING HOOK IN PICKUP MODE":                sim.Simvar,
		"IS ATTACHED TO SLING":                     sim.Simvar,
		"CABLE CAUGHT BY TAILHOOK":                 sim.Simvar,
		"EXTERNAL SYSTEM VALUE":                    sim.Simvar,
		"ANNUNCIATOR SWITCH":                       sim.Simvar,
		"AUTOBRAKES ACTIVE":                        sim.Simvar,
		"REJECTED TAKEOFF BRAKES ACTIVE":           sim.Simvar,
		"SHUTOFF VALVE PULLED":                     sim.Simvar,
		"LIGHT POTENTIOMETER":                      sim.Simvar,
		"FAKE AC LWR":                              sim.Simvar,
		"FAKE AC UPR":                              sim.Simvar,
		"FAKE AC TRIM L":                           sim.Simvar,
		"FAKE AC TRIM R":                           sim.Simvar,
		"FAKE WINDOW HEAT L":                       sim.Simvar,
		"FAKE WINDOW HEAT R":                       sim.Simvar,
		"FAKE BUS TIE":                             sim.Simvar,
		"FAKE EXT PWR":                             sim.Simvar,
		"FAKE GEN CONT":                            sim.Simvar,
		"FAKE UTIL PWR L":                          sim.Simvar,
		"FAKE UTIL PWR R":                          sim.Simvar,
		"FAKE CRT TANK PUMP L":                     sim.Simvar,
		"FAKE CRT TANK PUMP R":                     sim.Simvar,
		"FAKE FUEL MAIN AFT":                       sim.Simvar,
		"FAKE FUEL MAIN FWD":                       sim.Simvar,
		"FAKE FUEL OVRD AFT":                       sim.Simvar,
		"FAKE FUEL OVRD FWD":                       sim.Simvar,
		"FAKE STAB TANK PUMP L":                    sim.Simvar,
		"FAKE STAB TANK PUMP R":                    sim.Simvar,
		"FAKE HYD PUMP SWITCH":                     sim.Simvar,
		"FAKE O2 YD LOWER":                         sim.Simvar,
		"FAKE O2 YD UPPER":                         sim.Simvar,
		"FAKE APU BLEED":                           sim.Simvar,
		"FAKE BLEED":                               sim.Simvar,
		"FAKE ISOLATION VALVE L":                   sim.Simvar,
		"FAKE ISOLATION VALVE R":                   sim.Simvar,
		"FAKE AC FLT DECK":                         sim.Simvar,
		"FAKE AC PASS TEMP":                        sim.Simvar,
		"FAKE STANDBY POWER":                       sim.Simvar,
		"FAKE DEMAND PUMP SEL":                     sim.Simvar,
		"FAKE IRS C":                               sim.Simvar,
		"FAKE IRS L":                               sim.Simvar,
		"FAKE IRS R":                               sim.Simvar,
		"FAKE ANTI ICE NACELLE":                    sim.Simvar,
		"FAKE ANTI ICE WING":                       sim.Simvar,
		"FAKE OUTFLOW VALVES":                      sim.Simvar,
		"FAKE XFEED":                               sim.Simvar,
		"FAKE EEC":                                 sim.Simvar,
		"FAKE PACK":                                sim.Simvar,
		"FAKE EMERG LIGHTS":                        sim.Simvar,
		"FAKE TRIM STAB":                           sim.Simvar,
		"FAKE CARGO ARM AFT":                       sim.Simvar,
		"FAKE XPNDR":                               sim.Simvar,
		"FAKE IDENT":                               sim.Simvar,
		"FAKE NO SMOKING":                          sim.Simvar,
		"FAKE SEATBELTS":                           sim.Simvar,
		"FAKE CARGO TEMP":                          sim.Simvar,
		"FAKE EMERGENCY LIGHT":                     sim.Simvar,
		"AUTOPILOT DISENGAGED":                     sim.Simvar,
		"FAKE APU GEN SWITCH":                      sim.Simvar,
		"BREAKER AVNFAN":                           sim.Simvar,
		"BREAKER AUTOPILOT":                        sim.Simvar,
		"BREAKER GPS":                              sim.Simvar,
		"BREAKER NAVCOM1":                          sim.Simvar,
		"BREAKER NAVCOM2":                          sim.Simvar,
		"BREAKER NAVCOM3":                          sim.Simvar,
		"BREAKER ADF":                              sim.Simvar,
		"BREAKER XPNDR":                            sim.Simvar,
		"BREAKER FLAP":                             sim.Simvar,
		"BREAKER INST":                             sim.Simvar,
		"BREAKER AVNBUS1":                          sim.Simvar,
		"BREAKER AVNBUS2":                          sim.Simvar,
		"BREAKER TURNCOORD":                        sim.Simvar,
		"BREAKER INSTLTS":                          sim.Simvar,
		"BREAKER ALTFLD":                           sim.Simvar,
		"BREAKER WARN":                             sim.Simvar,
		"BREAKER LTS PWR":                          sim.Simvar,
		"PILOT TRANSMITTER TYPE":                   sim.Simvar,
		"COPILOT TRANSMITTER TYPE":                 sim.Simvar,
		"PILOT TRANSMITTING":                       sim.Simvar,
		"COPILOT TRANSMITTING":                     sim.Simvar,
		"SPEAKER ACTIVE":                           sim.Simvar,
		"INTERCOM SYSTEM ACTIVE":                   sim.Simvar,
		"AUDIO PANEL VOLUME":                       sim.Simvar,
		"MARKER BEACON SENSITIVITY HIGH":           sim.Simvar,
		"MARKER BEACON TEST MUTE":                  sim.Simvar,
		"INTERCOM MODE":                            sim.Simvar,
		"COM RECEIVE":                              sim.Simvar,
		"AUTOPILOT ALTITUDE ARM":                   sim.Simvar,
		"COM VOLUME":                               sim.Simvar,
		"NAV VOLUME":                               sim.Simvar,
		"ATC CLEARED IFR":                          sim.Simvar,
		"ATC IFR FP TO REQUEST":                    sim.Simvar,
		"ATC RUNWAY SELECTED":                      sim.Simvar,
		"ATC TAXIPATH DISTANCE":                    sim.Simvar,
		"ATC RUNWAY START DISTANCE":                sim.Simvar,
		"ATC RUNWAY END DISTANCE":                  sim.Simvar,
		"ATC RUNWAY DISTANCE":                      sim.Simvar,
		"ATC RUNWAY RELATIVE POSITION X":           sim.Simvar,
		"ATC RUNWAY RELATIVE POSITION Y":           sim.Simvar,
		"ATC RUNWAY RELATIVE POSITION Z":           sim.Simvar,
		"ATC RUNWAY TDPOINT RELATIVE POSITION X":   sim.Simvar,
		"ATC RUNWAY TDPOINT RELATIVE POSITION Y":   sim.Simvar,
		"ATC RUNWAY TDPOINT RELATIVE POSITION Z":   sim.Simvar,
		"ATC RUNWAY HEADING DEGREES TRUE":          sim.Simvar,
		"ATC RUNWAY LENGTH":                        sim.Simvar,
		"ATC RUNWAY WIDTH":                         sim.Simvar,
		"ATC RUNWAY AIRPORT NAME":                  sim.Simvar,
		"SLOPE TO ATC RUNWAY":                      sim.Simvar,
		"ATC CLEARED TAKEOFF":                      sim.Simvar,
		"ATC CLEARED LANDING":                      sim.Simvar,
		"ATC CLEARED TAXI":                         sim.Simvar,
		"ON ANY RUNWAY":                            sim.Simvar,
		"ATC FLIGHTPLAN DIFF HEADING":              sim.Simvar,
		"ATC FLIGHTPLAN DIFF ALT":                  sim.Simvar,
		"ATC FLIGHTPLAN DIFF DISTANCE":             sim.Simvar,
		"ATC PREVIOUS WAYPOINT ALTITUDE":           sim.Simvar,
		"ATC CURRENT WAYPOINT ALTITUDE":            sim.Simvar,
		"ASSISTANCE LANDING ENABLED":               sim.Simvar,
		"COM1 STORED FREQUENCY":                    sim.Simvar,
		"COM2 STORED FREQUENCY":                    sim.Simvar,
		"COM3 STORED FREQUENCY":                    sim.Simvar,
		"RUDDER TRIM DISABLED":                     sim.Simvar,
		"AILERON TRIM DISABLED":                    sim.Simvar,
		"ELEVATOR TRIM DISABLED":                   sim.Simvar,
		"PLANE TOUCHDOWN LATITUDE":                 sim.Simvar,
		"PLANE TOUCHDOWN LONGITUDE":                sim.Simvar,
		"PLANE TOUCHDOWN PITCH DEGREES":            sim.Simvar,
		"PLANE TOUCHDOWN BANK DEGREES":             sim.Simvar,
		"PLANE TOUCHDOWN HEADING DEGREES MAGNETIC": sim.Simvar,
		"PLANE TOUCHDOWN HEADING DEGREES TRUE":     sim.Simvar,
		"PLANE TOUCHDOWN NORMAL VELOCITY":          sim.Simvar,
		"TURB ENG IGNITION SWITCH EX1":             sim.Simvar,
		"TURB ENG IS IGNITING":                     sim.Simvar,
		"PLANE IN PARKING STATE":                   sim.Simvar,
		"ELT ACTIVATED":                            sim.Simvar,
		"RECIP ENG ENGINE MASTER SWITCH":           sim.Simvar,
		"RECIP ENG GLOW PLUG ACTIVE":               sim.Simvar,
		"LIGHT GLARESHIELD":                        sim.Simvar,
		"LIGHT PEDESTRAL":                          sim.Simvar,
		"LIGHT GLARESHIELD ON":                     sim.Simvar,
		"LIGHT PEDESTRAL ON":                       sim.Simvar,
		"CIRCUIT NAVCOM1 ON":                       sim.Simvar,
		"CIRCUIT NAVCOM2 ON":                       sim.Simvar,
		"CIRCUIT NAVCOM3 ON":                       sim.Simvar,
		"AIRSPEED TRUE RAW":                        sim.Simvar,
		"GENERAL ENG FUEL PUMP SWITCH EX1":         sim.Simvar,
		"FUEL TRANSFER PUMP ON":                    sim.Simvar,
		"IS ANY INTERIOR LIGHT ON":                 sim.Simvar,
		"GPS FLIGHTPLAN TOTAL DISTANCE":            sim.Simvar,
		"CIRCUIT ON":                               sim.Simvar,
		"CIRCUIT SWITCH ON":                        sim.Simvar,
		"BUS LOOKUP INDEX":                         sim.Simvar,
		"BUS CONNECTION ON":                        sim.Simvar,
		"BATTERY CONNECTION ON":                    sim.Simvar,
		"ALTERNATOR CONNECTION ON":                 sim.Simvar,
		"CIRCUIT CONNECTION ON":                    sim.Simvar,
		"BUS BREAKER PULLED":                       sim.Simvar,
		"BATTERY BREAKER PULLED":                   sim.Simvar,
		"ALTERNATOR BREAKER PULLED":                sim.Simvar,
		"CIRCUIT BREAKER PULLED":                   sim.Simvar,
		"CAMERA STATE":                             sim.Simvar,
		"CAMERA SUBSTATE":                          sim.Simvar,
		"SMART CAMERA ACTIVE":                      sim.Simvar,
		"CAMERA REQUEST ACTION":                    sim.Simvar,
		"ADF VOLUME":                               sim.Simvar,
		"BLEED AIR APU":                            sim.Simvar,
		"BLEED AIR ENGINE":                         sim.Simvar,
		"APU BLEED TO ENGINE":                      sim.Simvar,
		"EXTERNAL POWER CONNECTION ON":             sim.Simvar,
		"EXTERNAL POWER BREAKER PULLED":            sim.Simvar,
		"EXTERNAL POWER AVAILABLE":                 sim.Simvar,
		"EXTERNAL POWER ON":                        sim.Simvar,

		"FUEL TOTAL QUANTITY":                 sim.SimVarFuelTotalQuantity,
		"GENERAL ENG RPM":                     sim.SimVarGeneralEngRpm,
		"GPS ETA":                             sim.SimVarGpsEta,
		"RECIP ENG FUEL AVAILABLE":            sim.SimVarRecipEngFuelAvailable,
		"GENERAL ENG THROTTLE LEVER POSITION": sim.SimVarGeneralEngThrottleLeverPosition,

	*/
}
